# This workflow will build scrapy-cluster dockerfiles and push them to ecr
name: Scrapy Cluster CI

on:
  push:
    branches: [ kompose ]

jobs:
  build-scrapy:
    runs-on: ubuntu-latest
  
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image to dockerhub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ericmelz/creepy-crawler
        dockerfile: docker/crawler/Docker.py3
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}



