# This workflow will build scrapy-cluster dockerfiles and push them to ecr
name: Scrapy Cluster CI

on:
  push:
    branches:
    - kompose
    paths-ignore:
    - helm/crawler/environments/ci/version.yaml
    - helm/crawler/environments/dev/version.yaml

jobs:
  build-eric-crawler:

    runs-on: ubuntu-latest
    env:
      SKIP_STEPS: true  # Set this to false to run all steps
  
    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image to ecr
      if: env.SKIP_STEPS != 'true'
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: eric-crawler
        dockerfile: docker/crawler/Dockerfile.py3
        registry: 638173936794.dkr.ecr.us-east-1.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-eric-kafka-monitor:

    runs-on: ubuntu-latest
    env:
      SKIP_STEPS: true  # Set this to false to run all steps
  
    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image to ecr
      if: env.SKIP_STEPS != 'true'
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: eric-kafka-monitor
        dockerfile: docker/kafka-monitor/Dockerfile.py3
        registry: 638173936794.dkr.ecr.us-east-1.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-eric-redis-monitor:

    runs-on: ubuntu-latest
    env:
      SKIP_STEPS: true  # Set this to false to run all steps
  
    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image to ecr
      if: env.SKIP_STEPS != 'true'
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: eric-redis-monitor
        dockerfile: docker/redis-monitor/Dockerfile.py3
        registry: 638173936794.dkr.ecr.us-east-1.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-eric-crawler-rest:

    runs-on: ubuntu-latest
    env:
      SKIP_STEPS: true  # Set this to false to run all steps
  
    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image to ecr
      if: env.SKIP_STEPS != 'true'
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: eric-crawler-rest
        dockerfile: docker/rest/Dockerfile.py3
        registry: 638173936794.dkr.ecr.us-east-1.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  build-datadoggie:

    runs-on: ubuntu-latest
    env:
      SKIP_STEPS: true  # Set this to false to run all steps

    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image to ecr
      if: env.SKIP_STEPS != 'true'
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: datadoggie
        dockerfile: docker/datadoggie/Dockerfile.py3
        registry: 638173936794.dkr.ecr.us-east-1.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  record-ci-version:
    needs: [build-eric-kafka-monitor, build-eric-redis-monitor, build-eric-crawler-rest, build-eric-crawler, build-datadoggie]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name 'Github Actions (eric)'
        git config --global user.email 'eric@emelz.com'

    - name: write sha
      run: |
        echo "writing sha ${{ github.sha }}"
        echo "version: ${{ github.sha }}" > helm/crawler/environments/ci/version.yaml
        git config --global user.name 'Github Actions (eric)'
        git config --global user.email 'eric@emelz.com'
        cat helm/crawler/environments/ci/version.yaml
        git add helm/crawler/environments/ci/version.yaml
        git commit -m "Updated version with SHA"
        echo "before push"
        git push origin kompose
        echo "after push"

  deploy-crawler:
    needs: [record-ci-version]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Update kube config
      run: aws eks update-kubeconfig --name ci-eks-cluster   

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.x'

   - name: Deploy Helm Chart
      run: |
        helm upgrade --install ci-crawler ./helm/crawler --namespace default

    - name: Deploy
      uses: cloudposse/github-action-deploy-helmfile@main
      id: deploy
      with:
        aws-region: us-west-2
        cluster: ci-eks-cluster
        environment: ci
        namespace: ci
        helmfile-path: helm/crawler
        operation: deploy
        debug: false

  test-crawler:
    needs: [deploy-crawler]
    runs-on: ubuntu-latest

    steps:
    - name: Test kafka-monitor
      run: |
        echo "testing kafka-monitor"

    - name: Test redis-monitor
      run: |
        echo "testing redis-monitor"

    - name: Test rest
      run: |
        echo "testing rest"

    - name: Test crawler
      run: |
        echo "testing crawler"

    - name: Tear down
      run: |
        echo "tearing down crawler"


  promote-to-dev:
    needs: [test-crawler]
    runs-on: ubuntu-latest

    steps:
    - name: Copy sha
      run: |
        echo "copying ci sha to dev "

    - name: Deploy crawler helm to Dev cluster
      run: |
        echo "deploying to dev cluster "
